{
 "title": "Node GPU Metrics",
 "description": "NVIDIA Data Center GPU Manager (DCGM.",
 "tags": [
  "IB",
  "GPU"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "name",
    "label": "Host:",
    "query": "label_values(node_uname_info, nodename)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_uname_info{nodename=\"$name\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(node_uname_info{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU SM Clocks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(dcgm_sm_clock{instance=\"$node:$port\"}*1000000)"
    }
   ]
  },
  {
   "title": "GPU Memory Clocks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(dcgm_memory_clock{instance=\"$node:$port\"}*1000000)"
    }
   ]
  },
  {
   "title": "GPU Mem Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "dcgm_fb_used{instance=\"$node:$port\"}/(dcgm_fb_used{instance=\"$node:$port\"}+dcgm_fb_free{instance=\"$node:$port\"})",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "dcgm_gpu_utilization{instance=\"$node:$port\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Avg. Temperature",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 2 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(dcgm_gpu_temp{instance=\"$node:$port\"})"
    }
   ]
  },
  {
   "title": "GPU Total Power",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dcgm_power_usage{instance=\"$node:$port\"})"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "dcgm_power_usage{instance=\"$node:$port\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Mem Cpy Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "dcgm_mem_copy_utilization{instance=\"$node:$port\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Total Mem Cpy Utilization",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(dcgm_mem_copy_utilization{instance=\"$node:$port\"})"
    }
   ]
  },
  {
   "title": "GPU Total Utilization",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(dcgm_gpu_utilization{instance=\"$node:$port\"})"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "dcgm_gpu_temp{instance=\"$node:$port\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  }
 ]
}